export const BUSINESS_CATEGORIES = {
  food_beverage: {
    icon: 'UtensilsCrossed',
    label: { sw: 'Chakula & Vinywaji', en: 'Food & Beverages' },
    subcategories: {
      chapati_mandazi: { sw: 'Chapati / Mandazi', en: 'Chapati / Mandazi' },
      mama_mboga: { sw: 'Mama Mboga', en: 'Vegetable Seller' },
      juice_bar: { sw: 'Juisi na Matunda', en: 'Juice & Fruits' },
      fast_food: { sw: 'Chakula cha Haraka', en: 'Fast Food' },
      other_food: { sw: 'Chakula Kingine', en: 'Other Food' },
    },
    expenseCategories: [
      { key: 'ingredients', sw: 'Vifaa vya kupikia', en: 'Ingredients' },
      { key: 'packaging', sw: 'Mifuko / Vyombo', en: 'Packaging' },
      { key: 'gas_charcoal', sw: 'Gesi / Mkaa', en: 'Gas / Charcoal' },
      { key: 'transport', sw: 'Usafiri', en: 'Transport' },
      { key: 'rent_stall', sw: 'Pango la sehemu', en: 'Stall Rent' },
      { key: 'other', sw: 'Nyingine', en: 'Other' },
    ],
    incomeCategories: [
      { key: 'food_sale', sw: 'Chakula', en: 'Food' },
      { key: 'beverage_sale', sw: 'Vinywaji', en: 'Beverages' },
      { key: 'other_income', sw: 'Nyingine', en: 'Other' },
    ],
    templateProducts: {
      chapati_mandazi: [
        { name: 'Chapati', price: 80, unit: 'pc' },
        { name: 'Mandazi', price: 30, unit: 'pc' },
        { name: 'Samosas', price: 50, unit: 'pc' },
        { name: 'Bhajia', price: 60, unit: 'pc' },
        { name: 'Kaimati', price: 40, unit: 'pc' },
        { name: 'Chai ya Maziwa', price: 50, unit: 'cup' },
        { name: 'Chai ya Tangawizi', price: 60, unit: 'cup' },
        { name: 'Kahawa', price: 80, unit: 'cup' },
        { name: 'Mahamri', price: 30, unit: 'pc' },
        { name: 'Vitumbua', price: 50, unit: 'pc' },
      ],
      mama_mboga: [
        { name: 'Sukuma Wiki', price: 50, unit: 'bunch' },
        { name: 'Cabbage', price: 80, unit: 'pc' },
        { name: 'Nyanya', price: 20, unit: 'pc' },
        { name: 'Kitunguu', price: 30, unit: 'pc' },
        { name: 'Viazi', price: 120, unit: 'kg' },
        { name: 'Karoti', price: 60, unit: 'bunch' },
        { name: 'Pilipili Hoho', price: 15, unit: 'pc' },
        { name: 'Biringanya', price: 30, unit: 'pc' },
        { name: 'Mananasi', price: 100, unit: 'pc' },
        { name: 'Ndizi Mbivu', price: 80, unit: 'bunch' },
      ],
      juice_bar: [
        { name: 'Juisi ya Mango', price: 100, unit: 'glass' },
        { name: 'Juisi ya Passion', price: 120, unit: 'glass' },
        { name: 'Juisi ya Tikiti', price: 100, unit: 'glass' },
        { name: 'Juisi ya Machungwa', price: 80, unit: 'glass' },
        { name: 'Fresha ya Ndizi', price: 100, unit: 'glass' },
        { name: 'Smoothie ya Strawberry', price: 150, unit: 'glass' },
        { name: 'Tunda la Mango', price: 50, unit: 'pc' },
        { name: 'Ndizi Mbivu', price: 20, unit: 'pc' },
      ],
      fast_food: [
        { name: 'Fish & Chips', price: 250, unit: 'pc' },
        { name: 'Chicken Fry', price: 300, unit: 'pc' },
        { name: 'Chips', price: 150, unit: 'pc' },
        { name: 'Sausage', price: 80, unit: 'pc' },
        { name: 'Burger', price: 200, unit: 'pc' },
        { name: 'Smocha', price: 150, unit: 'pc' },
        { name: 'Mshikaki', price: 100, unit: 'pc' },
        { name: 'Mayai Chemsha', price: 50, unit: 'pc' },
      ],
      other_food: [
        { name: 'Ugali', price: 50, unit: 'pc' },
        { name: 'Nyama Choma', price: 500, unit: 'kg' },
        { name: 'Mukimo', price: 100, unit: 'pc' },
        { name: 'Githeri', price: 80, unit: 'pc' },
        { name: 'Biriani', price: 350, unit: 'pc' },
        { name: 'Pilau', price: 250, unit: 'pc' },
        { name: 'Mchele na Maharage', price: 150, unit: 'pc' },
        { name: 'Mbaazi', price: 80, unit: 'pc' },
        { name: 'Mokimo', price: 100, unit: 'pc' },
        { name: 'Wali wa Nazi', price: 120, unit: 'pc' },
      ],
    },
  },
  retail: {
    icon: 'ShoppingBag',
    label: { sw: 'Bidhaa & Rejareja', en: 'Retail & Trade' },
    subcategories: {
      kiosk_duka: { sw: 'Kiosk / Duka', en: 'Kiosk / Shop' },
      mtumba: { sw: 'Mtumba', en: 'Secondhand Clothes' },
      electronics: { sw: 'Simu & Elektroniki', en: 'Phones & Electronics' },
      cosmetics: { sw: 'Vipodozi', en: 'Cosmetics & Beauty' },
      household: { sw: 'Vitu vya Nyumbani', en: 'Household Items' },
      other_retail: { sw: 'Bidhaa Nyingine', en: 'Other Goods' },
    },
    expenseCategories: [
      { key: 'stock', sw: 'Bidhaa / Stoo', en: 'Stock / Inventory' },
      { key: 'transport', sw: 'Usafiri', en: 'Transport' },
      { key: 'rent_stall', sw: 'Pango la duka', en: 'Shop Rent' },
      { key: 'packaging', sw: 'Mifuko / Sanduku', en: 'Packaging' },
      { key: 'other', sw: 'Nyingine', en: 'Other' },
    ],
    incomeCategories: [
      { key: 'retail_sale', sw: 'Bidhaa', en: 'Goods' },
      { key: 'wholesale', sw: 'Jumla', en: 'Wholesale' },
      { key: 'other_income', sw: 'Nyingine', en: 'Other' },
    ],
    templateProducts: {
      kiosk_duka: [
        { name: 'Maji', price: 50, unit: 'btl' },
        { name: 'Soda', price: 50, unit: 'btl' },
        { name: 'Uji Power', price: 30, unit: 'pc' },
        { name: 'Biscuits', price: 20, unit: 'pc' },
        { name: 'Soap Bar', price: 35, unit: 'pc' },
        { name: 'Mchele', price: 200, unit: 'kg' },
        { name: 'Cooking Oil', price: 300, unit: 'L' },
        { name: 'Unga wa Mahindi', price: 180, unit: 'kg' },
        { name: 'Sugar', price: 250, unit: 'kg' },
        { name: 'Salt', price: 20, unit: 'pc' },
      ],
      mtumba: [
        { name: 'Trousers', price: 350, unit: 'pc' },
        { name: 'Shirt', price: 250, unit: 'pc' },
        { name: 'Jacket', price: 600, unit: 'pc' },
        { name: 'Shoes', price: 500, unit: 'pair' },
        { name: 'Skirt', price: 300, unit: 'pc' },
        { name: 'Dress', price: 400, unit: 'pc' },
        { name: 'Sweater', price: 350, unit: 'pc' },
        { name: 'Shorts', price: 200, unit: 'pc' },
        { name: 'T-shirt', price: 200, unit: 'pc' },
        { name: 'Jeans', price: 450, unit: 'pc' },
      ],
      electronics: [
        { name: 'Phone Charger', price: 300, unit: 'pc' },
        { name: 'Earphones', price: 250, unit: 'pc' },
        { name: 'Phone Case', price: 200, unit: 'pc' },
        { name: 'Power Bank', price: 1500, unit: 'pc' },
        { name: 'USB Cable', price: 150, unit: 'pc' },
        { name: 'Screen Guard', price: 200, unit: 'pc' },
        { name: 'Flash Disk', price: 800, unit: 'pc' },
        { name: 'Bluetooth Speaker', price: 1200, unit: 'pc' },
        { name: 'SIM Card', price: 100, unit: 'pc' },
        { name: 'Phone Pouch', price: 250, unit: 'pc' },
      ],
      cosmetics: [
        { name: 'Lipstick', price: 200, unit: 'pc' },
        { name: 'Foundation', price: 500, unit: 'pc' },
        { name: 'Mascara', price: 300, unit: 'pc' },
        { name: 'Nail Polish', price: 150, unit: 'pc' },
        { name: 'Perfume', price: 600, unit: 'btl' },
        { name: 'Body Lotion', price: 400, unit: 'btl' },
        { name: 'Hair Cream', price: 350, unit: 'pc' },
        { name: 'Face Wash', price: 250, unit: 'pc' },
        { name: 'Eye Pencil', price: 150, unit: 'pc' },
        { name: 'Blush', price: 250, unit: 'pc' },
      ],
      household: [
        { name: 'Plates', price: 150, unit: 'pc' },
        { name: 'Cups', price: 100, unit: 'pc' },
        { name: 'Sufuria', price: 600, unit: 'pc' },
        { name: 'Broom', price: 200, unit: 'pc' },
        { name: 'Buckets', price: 350, unit: 'pc' },
        { name: 'Cutting Board', price: 250, unit: 'pc' },
        { name: 'Knife Set', price: 400, unit: 'set' },
        { name: 'Spoon / Fork', price: 50, unit: 'pc' },
        { name: 'Basin', price: 300, unit: 'pc' },
        { name: 'Soap Dispenser', price: 200, unit: 'pc' },
      ],
      other_retail: [
        { name: 'Toothbrush', price: 80, unit: 'pc' },
        { name: 'Toothpaste', price: 150, unit: 'pc' },
        { name: 'Tissue Paper', price: 100, unit: 'pc' },
        { name: 'Matches', price: 20, unit: 'box' },
        { name: 'Candle', price: 50, unit: 'pc' },
        { name: 'Batteries', price: 100, unit: 'pair' },
        { name: 'Pen', price: 20, unit: 'pc' },
        { name: 'Exercise Book', price: 60, unit: 'pc' },
        { name: 'Razor Blade', price: 30, unit: 'pc' },
      ],
    },
  },
  jua_kali: {
    icon: 'Hammer',
    label: { sw: 'Jua Kali & Ufundi', en: 'Jua Kali & Artisan' },
    subcategories: {
      welder: { sw: 'Mchomaji / Welder', en: 'Welder' },
      carpenter: { sw: 'Seremala', en: 'Carpenter' },
      cobbler: { sw: 'Fundi wa Viatu', en: 'Cobbler' },
      tailor: { sw: 'Mshonaji', en: 'Tailor' },
      mechanic: { sw: 'Mekaniski', en: 'Mechanic' },
      other_jua_kali: { sw: 'Ufundi Mwingine', en: 'Other Artisan' },
    },
    expenseCategories: [
      { key: 'materials', sw: 'Vifaa / Malighafi', en: 'Materials' },
      { key: 'tools', sw: 'Zana za kazi', en: 'Tools' },
      { key: 'transport', sw: 'Usafiri', en: 'Transport' },
      { key: 'rent_workshop', sw: 'Pango la karakana', en: 'Workshop Rent' },
      { key: 'other', sw: 'Nyingine', en: 'Other' },
    ],
    incomeCategories: [
      { key: 'service_fee', sw: 'Huduma', en: 'Service' },
      { key: 'product_sale', sw: 'Bidhaa', en: 'Product' },
      { key: 'other_income', sw: 'Nyingine', en: 'Other' },
    ],
    templateProducts: {
      welder: [
        { name: 'Gate Repair', price: 2000, unit: 'pc' },
        { name: 'Window Grill', price: 3500, unit: 'pc' },
        { name: 'Door Frame', price: 3000, unit: 'pc' },
        { name: 'Metal Bed Frame', price: 5000, unit: 'pc' },
        { name: 'Shelf Bracket', price: 500, unit: 'pc' },
        { name: 'Chair Frame', price: 1500, unit: 'pc' },
        { name: 'Railing', price: 4000, unit: 'm' },
        { name: 'Garden Gate', price: 2500, unit: 'pc' },
      ],
      carpenter: [
        { name: 'Table', price: 3000, unit: 'pc' },
        { name: 'Chair', price: 1500, unit: 'pc' },
        { name: 'Bed', price: 8000, unit: 'pc' },
        { name: 'Wardrobe', price: 12000, unit: 'pc' },
        { name: 'Bookshelf', price: 4500, unit: 'pc' },
        { name: 'Window Frame', price: 2500, unit: 'pc' },
        { name: 'Door', price: 4000, unit: 'pc' },
        { name: 'Kitchen Cabinet', price: 10000, unit: 'pc' },
        { name: 'Stool', price: 800, unit: 'pc' },
      ],
      cobbler: [
        { name: 'Shoe Repair', price: 300, unit: 'pair' },
        { name: 'Shoe Polish', price: 100, unit: 'pc' },
        { name: 'Heel Replacement', price: 200, unit: 'pair' },
        { name: 'Shoe Stitching', price: 250, unit: 'pair' },
        { name: 'Bag Repair', price: 400, unit: 'pc' },
        { name: 'Belt Repair', price: 150, unit: 'pc' },
        { name: 'Zipper Replacement', price: 300, unit: 'pc' },
        { name: 'Shoe Stretch', price: 200, unit: 'pair' },
      ],
      tailor: [
        { name: 'Dress Making', price: 1000, unit: 'pc' },
        { name: 'Shirt Alteration', price: 300, unit: 'pc' },
        { name: 'Trouser Hem', price: 200, unit: 'pair' },
        { name: 'Suit Tailoring', price: 3500, unit: 'pc' },
        { name: 'Skirt Making', price: 800, unit: 'pc' },
        { name: 'Dress Alteration', price: 500, unit: 'pc' },
        { name: 'Button Replacement', price: 100, unit: 'pc' },
        { name: 'Patch / Darning', price: 200, unit: 'pc' },
        { name: 'Traditional Wear', price: 2000, unit: 'pc' },
      ],
      mechanic: [
        { name: 'Oil Change', price: 500, unit: 'pc' },
        { name: 'Tire Change', price: 300, unit: 'pc' },
        { name: 'Brake Pad', price: 2000, unit: 'set' },
        { name: 'Battery Check', price: 200, unit: 'pc' },
        { name: 'Spark Plug', price: 600, unit: 'set' },
        { name: 'Air Filter', price: 800, unit: 'pc' },
        { name: 'Wheel Alignment', price: 1500, unit: 'pc' },
        { name: 'Clutch Repair', price: 5000, unit: 'pc' },
        { name: 'Engine Tune Up', price: 3000, unit: 'pc' },
        { name: 'Wiper Blade', price: 500, unit: 'pair' },
      ],
      other_jua_kali: [
        { name: 'Masonry per day', price: 1500, unit: 'day' },
        { name: 'Painting per room', price: 2500, unit: 'room' },
        { name: 'Plumbing Repair', price: 1000, unit: 'pc' },
        { name: 'Electrical Fix', price: 800, unit: 'pc' },
        { name: 'Fumigation', price: 2000, unit: 'pc' },
        { name: 'Tiling per M²', price: 500, unit: 'm²' },
        { name: 'Roof Repair', price: 3000, unit: 'pc' },
        { name: 'Ceiling Installation', price: 2000, unit: 'room' },
      ],
    },
  },
  agriculture: {
    icon: 'Sprout',
    label: { sw: 'Kilimo & Mifugo', en: 'Agriculture & Livestock' },
    subcategories: {
      crops: { sw: 'Mazao ya Shamba', en: 'Crops' },
      poultry: { sw: 'Kuku & Mayai', en: 'Poultry & Eggs' },
      dairy: { sw: 'Maziwa', en: 'Dairy' },
      other_agri: { sw: 'Kilimo Kingine', en: 'Other Agriculture' },
    },
    expenseCategories: [
      { key: 'seeds_feeds', sw: 'Mbegu / Lishe', en: 'Seeds / Feed' },
      { key: 'labour', sw: 'Malipo ya Wafanyakazi', en: 'Labour' },
      { key: 'transport', sw: 'Usafiri', en: 'Transport' },
      { key: 'fertilizer', sw: 'Mbolea', en: 'Fertilizer / Medicine' },
      { key: 'other', sw: 'Nyingine', en: 'Other' },
    ],
    incomeCategories: [
      { key: 'produce_sale', sw: 'Mazao', en: 'Produce' },
      { key: 'livestock_sale', sw: 'Mifugo', en: 'Livestock' },
      { key: 'other_income', sw: 'Nyingine', en: 'Other' },
    ],
    templateProducts: {
      crops: [
        { name: 'Maize', price: 5000, unit: '90kg bag' },
        { name: 'Beans', price: 8000, unit: '90kg bag' },
        { name: 'Potatoes', price: 3000, unit: '50kg bag' },
        { name: 'Tomatoes', price: 200, unit: 'kg' },
        { name: 'Kale', price: 50, unit: 'bunch' },
        { name: 'Onions', price: 150, unit: 'kg' },
        { name: 'Cabbage', price: 60, unit: 'pc' },
        { name: 'Bananas', price: 500, unit: 'bunch' },
        { name: 'Avocado', price: 50, unit: 'pc' },
        { name: 'Sukuma Wiki', price: 40, unit: 'bunch' },
      ],
      poultry: [
        { name: 'Tray of Eggs', price: 550, unit: 'tray' },
        { name: 'Live Chicken', price: 600, unit: 'pc' },
        { name: 'Broiler Chicken', price: 800, unit: 'pc' },
        { name: 'kienyeji Chicken', price: 1200, unit: 'pc' },
        { name: 'Eggs (single)', price: 20, unit: 'pc' },
        { name: 'Chick', price: 200, unit: 'pc' },
        { name: 'Duck', price: 1500, unit: 'pc' },
        { name: 'Feed (Layer)', price: 2800, unit: '50kg bag' },
      ],
      dairy: [
        { name: 'Maziwa Fresh', price: 70, unit: 'L' },
        { name: 'Maliva', price: 80, unit: 'L' },
        { name: 'Nyama Choma', price: 600, unit: 'kg' },
        { name: 'Maziwa ya Kando', price: 60, unit: 'L' },
        { name: 'Goat Meat', price: 500, unit: 'kg' },
        { name: 'Beef', price: 550, unit: 'kg' },
        { name: 'Yoghurt', price: 150, unit: 'cup' },
        { name: 'Ghee', price: 800, unit: 'L' },
      ],
      other_agri: [
        { name: 'Honey', price: 600, unit: 'L' },
        { name: 'Fish (Tilapia)', price: 400, unit: 'pc' },
        { name: 'Fish (Omena)', price: 200, unit: 'kg' },
        { name: 'Mushroom', price: 500, unit: 'kg' },
        { name: 'Groundnuts', price: 300, unit: 'kg' },
        { name: 'Sunflower Seeds', price: 150, unit: 'kg' },
        { name: 'Hay Bale', price: 500, unit: 'pc' },
        { name: 'Manure (bag)', price: 300, unit: '50kg bag' },
      ],
    },
  },
  services: {
    icon: 'Scissors',
    label: { sw: 'Huduma', en: 'Personal Services' },
    subcategories: {
      salon_barber: { sw: 'Saluni / Kinyozi', en: 'Salon / Barber' },
      laundry: { sw: 'Dobi / Piga Pasi', en: 'Laundry / Ironing' },
      cleaning: { sw: 'Usafi', en: 'Cleaning Services' },
      other_services: { sw: 'Huduma Nyingine', en: 'Other Services' },
    },
    expenseCategories: [
      { key: 'supplies', sw: 'Vifaa vya kazi', en: 'Work Supplies' },
      { key: 'rent', sw: 'Pango', en: 'Rent' },
      { key: 'transport', sw: 'Usafiri', en: 'Transport' },
      { key: 'other', sw: 'Nyingine', en: 'Other' },
    ],
    incomeCategories: [
      { key: 'service_fee', sw: 'Huduma', en: 'Service' },
      { key: 'product_sale', sw: 'Bidhaa', en: 'Product' },
      { key: 'other_income', sw: 'Nyingine', en: 'Other' },
    ],
    templateProducts: {
      salon_barber: [
        { name: 'Haircut', price: 300, unit: 'pc' },
        { name: 'Shave', price: 200, unit: 'pc' },
        { name: 'Plaits', price: 800, unit: 'pc' },
        { name: 'Hair Blow Dry', price: 500, unit: 'pc' },
        { name: 'Manicure', price: 600, unit: 'pc' },
        { name: 'Pedicure', price: 700, unit: 'pc' },
        { name: 'Shampoo & Condition', price: 400, unit: 'pc' },
        { name: 'Beard Trim', price: 200, unit: 'pc' },
        { name: 'Hair Dye', price: 1500, unit: 'pc' },
        { name: 'Facial', price: 800, unit: 'pc' },
      ],
      laundry: [
        { name: 'Shirt Wash & Iron', price: 100, unit: 'pc' },
        { name: 'Trousers Wash', price: 100, unit: 'pair' },
        { name: 'Full Suit Dry Clean', price: 400, unit: 'pc' },
        { name: 'Dress Wash', price: 150, unit: 'pc' },
        { name: 'Bed Sheet', price: 150, unit: 'pc' },
        { name: 'Iron Only', price: 50, unit: 'pc' },
        { name: 'Duvet Wash', price: 500, unit: 'pc' },
        { name: 'Curtain Wash', price: 300, unit: 'pc' },
      ],
      cleaning: [
        { name: 'House Cleaning', price: 2000, unit: 'pc' },
        { name: 'Office Cleaning', price: 3000, unit: 'pc' },
        { name: 'Carpet Wash', price: 500, unit: 'm²' },
        { name: 'Window Cleaning', price: 1500, unit: 'session' },
        { name: 'Sofa Wash', price: 2000, unit: 'pc' },
        { name: 'Pressure Wash', price: 3000, unit: 'session' },
        { name: 'Move Out Clean', price: 5000, unit: 'pc' },
        { name: 'Toilet Deep Clean', price: 800, unit: 'pc' },
      ],
      other_services: [
        { name: 'Photography', price: 3000, unit: 'session' },
        { name: 'Event Planning', price: 5000, unit: 'event' },
        { name: 'Tutoring per hour', price: 500, unit: 'hour' },
        { name: 'Massage', price: 1500, unit: 'session' },
        { name: 'Car Wash', price: 300, unit: 'pc' },
        { name: 'Dog Grooming', price: 1000, unit: 'pc' },
        { name: 'Shoe Shine', price: 100, unit: 'pair' },
        { name: 'Mobile Money Help', price: 50, unit: 'pc' },
      ],
    },
  },
  transport: {
    icon: 'Bike',
    label: { sw: 'Usafiri', en: 'Transport' },
    subcategories: {
      boda_boda: { sw: 'Boda Boda', en: 'Boda Boda' },
      tuk_tuk: { sw: 'Tuk Tuk', en: 'Tuk Tuk' },
      mkokoteni: { sw: 'Mkokoteni / Baiskeli', en: 'Cart / Bicycle' },
      other_transport: { sw: 'Usafiri Mwingine', en: 'Other Transport' },
    },
    expenseCategories: [
      { key: 'fuel', sw: 'Mafuta', en: 'Fuel' },
      { key: 'repairs', sw: 'Matengenezo', en: 'Repairs' },
      { key: 'insurance', sw: 'Bima', en: 'Insurance / NTSA' },
      { key: 'other', sw: 'Nyingine', en: 'Other' },
    ],
    incomeCategories: [
      { key: 'fare', sw: 'Nauli', en: 'Fare' },
      { key: 'delivery', sw: 'Usafirishaji', en: 'Delivery' },
      { key: 'other_income', sw: 'Nyingine', en: 'Other' },
    ],
    templateProducts: {
      boda_boda: [
        { name: 'Short Trip', price: 100, unit: 'trip' },
        { name: 'Medium Trip', price: 200, unit: 'trip' },
        { name: 'Long Trip', price: 500, unit: 'trip' },
        { name: 'Package Delivery', price: 150, unit: 'pc' },
        { name: 'Food Delivery', price: 100, unit: 'pc' },
        { name: 'Airport Run', price: 800, unit: 'trip' },
        { name: 'Night Trip', price: 300, unit: 'trip' },
        { name: 'Hourly Hire', price: 300, unit: 'hour' },
        { name: 'Full Day Hire', price: 1500, unit: 'day' },
        { name: 'Cargo Transport', price: 500, unit: 'pc' },
      ],
      tuk_tuk: [
        { name: 'Short Trip', price: 150, unit: 'trip' },
        { name: 'Medium Trip', price: 300, unit: 'trip' },
        { name: 'Town Run', price: 200, unit: 'trip' },
        { name: 'Market Trip', price: 400, unit: 'trip' },
        { name: 'Goods Transport', price: 500, unit: 'pc' },
        { name: 'Hourly Hire', price: 500, unit: 'hour' },
        { name: 'Half Day', price: 2000, unit: 'trip' },
        { name: 'Full Day Hire', price: 3000, unit: 'day' },
      ],
      mkokoteni: [
        { name: 'Market Transport', price: 200, unit: 'trip' },
        { name: 'Shop Delivery', price: 300, unit: 'trip' },
        { name: 'Construction Load', price: 500, unit: 'trip' },
        { name: 'Sugarcane Load', price: 400, unit: 'trip' },
        { name: 'Wood Transport', price: 600, unit: 'trip' },
        { name: 'Half Day Hire', price: 800, unit: 'trip' },
        { name: 'Full Day Hire', price: 1200, unit: 'day' },
        { name: 'Sambaza Load', price: 250, unit: 'trip' },
      ],
      other_transport: [
        { name: 'Taxi Short Trip', price: 500, unit: 'trip' },
        { name: 'Taxi Long Trip', price: 2000, unit: 'trip' },
        { name: 'Airport Transfer', price: 2500, unit: 'trip' },
        { name: 'School Run', price: 300, unit: 'trip' },
        { name: 'Group Transport', price: 1500, unit: 'trip' },
        { name: 'Night Taxi', price: 1000, unit: 'trip' },
        { name: 'Intercity Trip', price: 5000, unit: 'trip' },
        { name: 'Cargo Van', price: 3000, unit: 'trip' },
      ],
    },
  },
  professional: {
    icon: 'Briefcase',
    label: { sw: 'Wakala & Huduma za Kitaalamu', en: 'Agents & Professional' },
    subcategories: {
      mpesa_agent: { sw: 'Wakala wa M-Pesa', en: 'M-Pesa Agent' },
      insurance: { sw: 'Wakala wa Bima', en: 'Insurance Agent' },
      other_professional: { sw: 'Huduma Nyingine', en: 'Other Professional' },
    },
    expenseCategories: [
      { key: 'float', sw: 'Float ya M-Pesa', en: 'M-Pesa Float' },
      { key: 'rent', sw: 'Pango', en: 'Rent' },
      { key: 'airtime', sw: 'Airtime / Data', en: 'Airtime / Data' },
      { key: 'other', sw: 'Nyingine', en: 'Other' },
    ],
    incomeCategories: [
      { key: 'service_fee', sw: 'Huduma', en: 'Service Fee' },
      { key: 'commission', sw: 'Tume', en: 'Commission' },
      { key: 'other_income', sw: 'Nyingine', en: 'Other' },
    ],
    templateProducts: {
      mpesa_agent: [
        { name: 'Send Money', price: 50, unit: 'txn' },
        { name: 'Withdraw Cash', price: 50, unit: 'txn' },
        { name: 'Airtime Purchase', price: 10, unit: 'txn' },
        { name: 'Pochi La Biashara', price: 50, unit: 'txn' },
        { name: 'Buy Goods Till', price: 30, unit: 'txn' },
        { name: 'M-Shwari Deposit', price: 30, unit: 'txn' },
        { name: 'KCB-MPesa Deposit', price: 30, unit: 'txn' },
        { name: 'Fuliza Payment', price: 30, unit: 'txn' },
        { name: 'Cash Power Token', price: 20, unit: 'txn' },
        { name: 'Bill Payment', price: 50, unit: 'txn' },
      ],
      insurance: [
        { name: 'Motor Insurance', price: 5000, unit: 'policy' },
        { name: 'Health Cover', price: 3000, unit: 'policy' },
        { name: 'Life Insurance', price: 2000, unit: 'policy' },
        { name: 'Travel Insurance', price: 2500, unit: 'policy' },
        { name: 'Business Insurance', price: 8000, unit: 'policy' },
        { name: 'Education Policy', price: 5000, unit: 'policy' },
        { name: 'Funeral Cover', price: 1500, unit: 'policy' },
        { name: 'Crop Insurance', price: 4000, unit: 'policy' },
        { name: 'Fire / Theft', price: 6000, unit: 'policy' },
        { name: 'Marine Insurance', price: 10000, unit: 'policy' },
      ],
      other_professional: [
        { name: 'Consultation Fee', price: 2000, unit: 'session' },
        { name: 'Legal Advice', price: 3000, unit: 'session' },
        { name: 'Accounting Service', price: 2500, unit: 'pc' },
        { name: 'IT Support', price: 1500, unit: 'hour' },
        { name: 'Graphic Design', price: 2000, unit: 'pc' },
        { name: 'Website Design', price: 15000, unit: 'pc' },
        { name: 'Writing Service', price: 1000, unit: 'pc' },
        { name: 'Translation Service', price: 500, unit: 'page' },
        { name: 'Training per day', price: 5000, unit: 'day' },
        { name: 'Social Media Mgmt', price: 8000, unit: 'month' },
      ],
    },
  },
} as const;

export type BusinessCategoryKey = keyof typeof BUSINESS_CATEGORIES;
export type BusinessCategory = typeof BUSINESS_CATEGORIES[BusinessCategoryKey];

export const categoryEmoji: Record<BusinessCategoryKey, string> = {
  food_beverage: '\u{1F37D}\uFE0F',
  retail: '\u{1F6CD}\uFE0F',
  jua_kali: '\u{1F527}',
  agriculture: '\u{1F331}',
  services: '\u{2702}\uFE0F',
  transport: '\u{1F6F5}',
  professional: '\u{1F4BC}',
};

export const CATEGORY_DASHBOARD_LABELS: Record<BusinessCategoryKey, {
  incomeLabel: { sw: string; en: string };
  expenseLabel: { sw: string; en: string };
  emptyTitle: { sw: string; en: string };
  emptyDesc: { sw: string; en: string };
  emptyWeekTitle: { sw: string; en: string };
  emptyWeekDesc: { sw: string; en: string };
}> = {
  food_beverage: {
    incomeLabel: { sw: 'Mauzo', en: 'Sales' },
    expenseLabel: { sw: 'Gharama', en: 'Costs' },
    emptyTitle: { sw: 'Bado hakuna mauzo leo', en: 'No sales yet today' },
    emptyDesc: { sw: 'Bonyeza + kuongeza mauzo', en: 'Tap + to add a sale' },
    emptyWeekTitle: { sw: 'Bado hakuna mauzo wiki hii', en: 'No sales yet this week' },
    emptyWeekDesc: { sw: 'Mauzo yako yataonekana hapa', en: 'Your sales will appear here' },
  },
  retail: {
    incomeLabel: { sw: 'Mauzo', en: 'Sales' },
    expenseLabel: { sw: 'Gharama', en: 'Costs' },
    emptyTitle: { sw: 'Bado hakuna mauzo leo', en: 'No sales today' },
    emptyDesc: { sw: 'Bonyeza + kuongeza bidhaa', en: 'Tap + to add goods' },
    emptyWeekTitle: { sw: 'Bado hakuna mauzo wiki hii', en: 'No sales this week' },
    emptyWeekDesc: { sw: 'Mauzo yako yataonekana hapa', en: 'Your sales will appear here' },
  },
  jua_kali: {
    incomeLabel: { sw: 'Malipo', en: 'Earnings' },
    expenseLabel: { sw: 'Gharama', en: 'Costs' },
    emptyTitle: { sw: 'Bado hakuna malipo leo', en: 'No earnings yet today' },
    emptyDesc: { sw: 'Bonyeza + kuweka huduma', en: 'Tap + to record service' },
    emptyWeekTitle: { sw: 'Bado hakuna malipo wiki hii', en: 'No earnings this week' },
    emptyWeekDesc: { sw: 'Malipo yako yataonekana hapa', en: 'Your earnings will appear here' },
  },
  agriculture: {
    incomeLabel: { sw: 'Mavuno', en: 'Harvest Sales' },
    expenseLabel: { sw: 'Gharama', en: 'Costs' },
    emptyTitle: { sw: 'Bado hakuna mavuno leo', en: 'No harvest sales today' },
    emptyDesc: { sw: 'Bonyeza + kuongeza mazao', en: 'Tap + to add produce' },
    emptyWeekTitle: { sw: 'Bado hakuna mavuno wiki hii', en: 'No harvest sales this week' },
    emptyWeekDesc: { sw: 'Mauzo yako yataonekana hapa', en: 'Your sales will appear here' },
  },
  services: {
    incomeLabel: { sw: 'Malipo', en: 'Service Fee' },
    expenseLabel: { sw: 'Gharama', en: 'Costs' },
    emptyTitle: { sw: 'Bado hakuna huduma leo', en: 'No services today' },
    emptyDesc: { sw: 'Bonyeza + kuweka huduma', en: 'Tap + to log a service' },
    emptyWeekTitle: { sw: 'Bado hakuna huduma wiki hii', en: 'No services this week' },
    emptyWeekDesc: { sw: 'Huduma zako zitaonekana hapa', en: 'Your services will appear here' },
  },
  transport: {
    incomeLabel: { sw: 'Nauli', en: 'Fares' },
    expenseLabel: { sw: 'Gharama', en: 'Costs' },
    emptyTitle: { sw: 'Bado hakuna nauli leo', en: 'No fares today' },
    emptyDesc: { sw: 'Bonyeza + kuweka nauli', en: 'Tap + to record a fare' },
    emptyWeekTitle: { sw: 'Bado hakuna nauli wiki hii', en: 'No fares this week' },
    emptyWeekDesc: { sw: 'Nauli zako zitaonekana hapa', en: 'Your fares will appear here' },
  },
  professional: {
    incomeLabel: { sw: 'Tume', en: 'Commission' },
    expenseLabel: { sw: 'Gharama', en: 'Costs' },
    emptyTitle: { sw: 'Bado hakuna tume leo', en: 'No commission today' },
    emptyDesc: { sw: 'Bonyeza + kuweka tume', en: 'Tap + to record commission' },
    emptyWeekTitle: { sw: 'Bado hakuna tume wiki hii', en: 'No commission this week' },
    emptyWeekDesc: { sw: 'Tume zako zitaonekana hapa', en: 'Your commissions will appear here' },
  },
};

export function getTemplateProducts(
  category: BusinessCategoryKey,
  subcategory: string
): Array<{ name: string; price: number; unit: string }> | undefined {
  const cat = BUSINESS_CATEGORIES[category];
  if (!cat) return undefined;
  const key = 'templateProducts' in cat ? (cat as unknown as Record<string, unknown>).templateProducts : undefined;
  if (!key) return undefined;
  const tps = cat as unknown as {
    templateProducts: Record<string, Array<{ name: string; price: number; unit: string }>>;
  };
  return tps.templateProducts[subcategory];
}

export function getCategoryLabels(lang: 'sw' | 'en'): Array<{ key: BusinessCategoryKey; label: string }> {
  return (Object.entries(BUSINESS_CATEGORIES) as [BusinessCategoryKey, typeof BUSINESS_CATEGORIES[BusinessCategoryKey]][]).map(
    ([key, cat]) => ({ key, label: cat.label[lang] })
  );
}
